name: Python package tests

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: "0 12 * * 1"
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  check-data-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Check data cache
        id: cache-data
        uses: actions/cache@v4
        with:
          path: quartz_solar_forecast/models
          key: ${{ runner.os }}-model-cache-${{ hashFiles('quartz_solar_forecast/models/**') }}
          restore-keys: |
            ${{ runner.os }}-model-cache-

  call-run-python-tests-unit:
    uses: openclimatefix/.github/.github/workflows/python-test.yml@issue/pip-all
    with:
      pytest_cov_dir: "quartz_solar_forecast"  # pytest-cov looks at this folder
      os_list: '["ubuntu-latest"]'
      python-version: "['3.11']"
      extra_commands: 
        echo "HF_TOKEN=${{ vars.HF_TOKEN }}" > .env
        export PYTEST_ADDOPTS="-v --durations=0"
      pytest_numcpus: '2'
      test_dir: tests/unit

  call-run-python-tests-all:
    needs: check-data-cache
    uses: openclimatefix/.github/.github/workflows/python-test.yml@issue/pip-all
    if: github.event_name == 'push'  # only run on push, not external PR
    with:
      pytest_cov_dir: "quartz_solar_forecast"  # pytest-cov looks at this folder
      os_list: '["ubuntu-latest"]'
      python-version: "['3.11']"
      extra_commands: 
        echo "HF_TOKEN=${{ vars.HF_TOKEN }}" > .env
        export PYTEST_ADDOPTS="-v --durations=0"
      pytest_numcpus: '2'
      test_dir: tests